<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Exsiting values in table not Present]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="103270" started-at="2018-12-23T16:20:25Z" finished-at="2018-12-23T16:22:09Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="103270" started-at="2018-12-23T16:20:25Z" finished-at="2018-12-23T16:22:09Z">
      <class name="script.FTMS_Web_Monitoring">
        <test-method status="PASS" signature="extentreport()[pri:0, instance:script.FTMS_Web_Monitoring@2ef5e5e3]" name="extentreport" is-config="true" duration-ms="291" started-at="2018-12-23T21:50:25Z" finished-at="2018-12-23T21:50:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentreport -->
        <test-method status="PASS" signature="OpenApp()[pri:0, instance:script.FTMS_Web_Monitoring@2ef5e5e3]" name="OpenApp" is-config="true" duration-ms="5677" started-at="2018-12-23T21:50:26Z" finished-at="2018-12-23T21:50:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenApp -->
        <test-method status="FAIL" signature="Monitering_from_Webside()[pri:0, instance:script.FTMS_Web_Monitoring@2ef5e5e3]" name="Monitering_from_Webside" duration-ms="93169" started-at="2018-12-23T21:50:31Z" finished-at="2018-12-23T21:52:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at generic.BasePage.VerifyElement(BasePage.java:63)
	at utilities.HomePage.DropButtonElement(HomePage.java:62)
	at script.FTMS_Web_Monitoring.Monitering_from_Webside(FTMS_Web_Monitoring.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Exsiting values in table not Present]]>
            </line>
          </reporter-output>
        </test-method> <!-- Monitering_from_Webside -->
        <test-method status="PASS" signature="ReportsandCloseApp(org.testng.ITestResult)[pri:0, instance:script.FTMS_Web_Monitoring@2ef5e5e3]" name="ReportsandCloseApp" is-config="true" duration-ms="3683" started-at="2018-12-23T21:52:05Z" finished-at="2018-12-23T21:52:08Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=Monitering_from_Webside status=FAILURE method=FTMS_Web_Monitoring.Monitering_from_Webside()[pri:0, instance:script.FTMS_Web_Monitoring@2ef5e5e3] output=Exsiting values in table not Present]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ReportsandCloseApp -->
        <test-method status="PASS" signature="Writeextentreport()[pri:0, instance:script.FTMS_Web_Monitoring@2ef5e5e3]" name="Writeextentreport" is-config="true" duration-ms="410" started-at="2018-12-23T21:52:08Z" finished-at="2018-12-23T21:52:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Writeextentreport -->
      </class> <!-- script.FTMS_Web_Monitoring -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
